import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
const DEFAULT_FROM = "uRide Insurance360 <noreply@uridehub.com>";

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    if (user.role !== 'admin') return Response.json({ error: 'Forbidden — admin only' }, { status: 403 });

    const { evidence_id, recipient_email } = await req.json();

    if (!evidence_id || !recipient_email) {
      return Response.json({ error: 'evidence_id and recipient_email are required' }, { status: 400 });
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(recipient_email)) {
      return Response.json({ error: 'Invalid email address' }, { status: 400 });
    }

    // Fetch the evidence record
    const records = await base44.asServiceRole.entities.EvidenceVault.filter({ id: evidence_id });
    const evidence = records[0];
    if (!evidence) return Response.json({ error: 'Evidence record not found' }, { status: 404 });

    // Build the email HTML
    const reportHtml = (evidence.ai_report_content || 'No report content available.')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/\n/g, '<br/>');

    const findingsHtml = (evidence.ai_findings || []).map(f => `<li>${f.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</li>`).join('');
    const recommendationsHtml = (evidence.ai_recommendations || []).map(r => `<li>${r.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</li>`).join('');
    const photoLinksHtml = (evidence.evidence_urls || []).map((url, i) => `<a href="${url}" style="display:inline-block;margin:4px;">Photo ${i + 1}</a>`).join(' ');

    const confidencePct = evidence.ai_confidence_score != null
      ? `${(evidence.ai_confidence_score * 100).toFixed(0)}%`
      : 'N/A';

    const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>${evidence.title}</title></head>
<body style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #1a1a1a;">
  <div style="background: linear-gradient(135deg, #e91e63, #7c3aed); padding: 24px; border-radius: 12px; margin-bottom: 24px;">
    <h1 style="color: white; margin: 0; font-size: 22px;">uRide Insurance360 — Audit Report</h1>
    <p style="color: rgba(255,255,255,0.85); margin: 8px 0 0; font-size: 14px;">${evidence.title}</p>
  </div>

  <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 13px;">
    <tr><td style="padding: 6px 12px; background: #f5f5f5; border: 1px solid #ddd; width: 180px; font-weight: bold;">Report Type</td><td style="padding: 6px 12px; border: 1px solid #ddd;">${evidence.evidence_type?.replace(/_/g, ' ') || 'Insurance Report'}</td></tr>
    <tr><td style="padding: 6px 12px; background: #f5f5f5; border: 1px solid #ddd; font-weight: bold;">Vehicle</td><td style="padding: 6px 12px; border: 1px solid #ddd;">${evidence.vehicle_name || 'N/A'}</td></tr>
    <tr><td style="padding: 6px 12px; background: #f5f5f5; border: 1px solid #ddd; font-weight: bold;">Generated By</td><td style="padding: 6px 12px; border: 1px solid #ddd;">${evidence.created_by || 'uRide Admin'}</td></tr>
    <tr><td style="padding: 6px 12px; background: #f5f5f5; border: 1px solid #ddd; font-weight: bold;">Confidence Score</td><td style="padding: 6px 12px; border: 1px solid #ddd;">${confidencePct}</td></tr>
    <tr><td style="padding: 6px 12px; background: #f5f5f5; border: 1px solid #ddd; font-weight: bold;">Date Generated</td><td style="padding: 6px 12px; border: 1px solid #ddd;">${evidence.evidence_date ? new Date(evidence.evidence_date).toLocaleString() : 'N/A'}</td></tr>
  </table>

  ${evidence.ai_report_summary ? `
  <h2 style="font-size: 16px; color: #e91e63; border-bottom: 2px solid #e91e63; padding-bottom: 4px;">Executive Summary</h2>
  <p style="font-size: 14px; line-height: 1.6;">${evidence.ai_report_summary}</p>
  ` : ''}

  ${findingsHtml ? `
  <h2 style="font-size: 16px; color: #e91e63; border-bottom: 2px solid #e91e63; padding-bottom: 4px; margin-top: 24px;">Key Findings</h2>
  <ul style="font-size: 14px; line-height: 1.8;">${findingsHtml}</ul>
  ` : ''}

  ${recommendationsHtml ? `
  <h2 style="font-size: 16px; color: #7c3aed; border-bottom: 2px solid #7c3aed; padding-bottom: 4px; margin-top: 24px;">Recommendations</h2>
  <ul style="font-size: 14px; line-height: 1.8;">${recommendationsHtml}</ul>
  ` : ''}

  <h2 style="font-size: 16px; color: #333; border-bottom: 2px solid #ddd; padding-bottom: 4px; margin-top: 24px;">Full Report</h2>
  <div style="font-size: 13px; line-height: 1.7; white-space: pre-wrap; background: #fafafa; padding: 16px; border-radius: 8px; border: 1px solid #eee;">${reportHtml}</div>

  ${photoLinksHtml ? `
  <h2 style="font-size: 16px; color: #333; border-bottom: 2px solid #ddd; padding-bottom: 4px; margin-top: 24px;">Evidence Photos</h2>
  <div style="font-size: 13px; padding: 12px;">${photoLinksHtml}</div>
  ` : ''}

  <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #999;">
    <p>This report was generated by uRide Insurance360 and transmitted on ${new Date().toLocaleString()}.</p>
    <p>Evidence ID: ${evidence.id}</p>
    <p>This is an automated transmission. For questions, contact the sender directly.</p>
  </div>
</body>
</html>`;

    // Send the email via Resend
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: DEFAULT_FROM,
        to: [recipient_email],
        subject: `uRide Insurance360 — ${evidence.title}`,
        html,
      }),
    });

    const data = await res.json();
    if (!res.ok) {
      console.error("[transmitInsuranceReport] Resend error:", JSON.stringify(data));
      return Response.json({ error: data.message || "Email delivery failed" }, { status: res.status });
    }

    // Update evidence record to transmitted
    await base44.asServiceRole.entities.EvidenceVault.update(evidence_id, {
      status: 'transmitted',
      transmitted_to: recipient_email,
      transmitted_at: new Date().toISOString(),
      transmission_method: 'email',
      transmission_notes: `Email sent via Resend (ID: ${data.id}) to ${recipient_email}`,
    });

    return Response.json({
      success: true,
      message: `Report transmitted to ${recipient_email}`,
      email_id: data.id,
    });
  } catch (error) {
    console.error("[transmitInsuranceReport] Error:", error.message);
    return Response.json({ error: error.message }, { status: 500 });
  }
});